gamer:
    resource: "@GamerBundle/Controller/"
    type:     annotation
    prefix:   /gamer



fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    type:     annotation
    prefix:   /
