#user:
#    resource: "@UserBundle/Controller/"
#    type:     annotation
#    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /

gamer:
    resource: "@GamerBundle/Controller/"
    type:     annotation
    prefix:   /



